---
- name: Set git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  when: git_user_name | length > 0
  tags: ['git']

- name: Set git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  when: git_user_email | length > 0
  tags: ['git']

- name: Set default branch to main
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags: ['git']

- name: Set pull strategy
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: "false"
  tags: ['git']

- name: Set git alias - adog (pretty log)
  community.general.git_config:
    name: alias.adog
    scope: global
    value: "log --all --decorate --oneline --graph"
  tags: ['git']
